// Easy: common, short, familiar words
export const EASY_WORDS: string[] = [
  'APPLE', 'BEACH', 'BREAD', 'CHAIR', 'CLOCK',
  'CLOUD', 'DANCE', 'DRINK', 'EARTH', 'FIELD',
  'FRUIT', 'GLASS', 'GRAPE', 'GREEN', 'HEART',
  'HOUSE', 'JUICE', 'LEMON', 'LIGHT', 'MUSIC',
  'NIGHT', 'OCEAN', 'PHONE', 'PIZZA', 'PLANT',
  'RADIO', 'RIVER', 'SHIRT', 'SHOES', 'SMILE',
  'SNAKE', 'SPACE', 'SPOON', 'STORM', 'TABLE',
  'TIGER', 'TOAST', 'TRAIN', 'TRUCK', 'VOICE',
  'WATCH', 'WATER', 'WHALE', 'WORLD', 'YOUTH',
];

// Medium: slightly less common
export const MEDIUM_WORDS: string[] = [
  'BRAIN', 'BRUSH', 'CHEST', 'CHORD', 'CLICK',
  'DIARY', 'DRIVE', 'FEAST', 'GUARD', 'PIANO',
  'PILOT', 'PLANE', 'ROBOT', 'TOUCH', 'WRITE',
  'BLAZE', 'CRISP', 'DWARF', 'FLAIR', 'GLOOM',
  'GROAN', 'HASTE', 'KNEEL', 'LODGE', 'MAPLE',
  'NERVE', 'ORBIT', 'PERCH', 'QUILT', 'RIDGE',
  'SCALP', 'SHRUG', 'SLUMP', 'SNARE', 'SPIRE',
  'STOMP', 'SWAMP', 'THORN', 'TROUT', 'VAULT',
  'WALTZ', 'WHIRL', 'WRATH', 'ZEBRA', 'ZONAL',
];

// Hard: uncommon or tricky words
export const HARD_WORDS: string[] = [
  'ABBEY', 'AXIOM', 'BLUNT', 'BYLAW', 'CHASM',
  'CINCH', 'CLEFT', 'CRYPT', 'CYNIC', 'DIRGE',
  'DROSS', 'EPOCH', 'EXPEL', 'EXTOL', 'FJORD',
  'FLECK', 'FROZE', 'GLYPH', 'GNASH', 'GRUFF',
  'GUILD', 'GUSTO', 'GYPSY', 'HAVOC', 'HELIX',
  'HIPPO', 'HOVEL', 'HYENA', 'IGLOO', 'INEPT',
  'IRONY', 'IVORY', 'JAZZY', 'JOUST', 'KNACK',
  'KNAVE', 'LYMPH', 'MAXIM', 'MELEE', 'MIRTH',
  'MOULT', 'MURKY', 'MYRRH', 'NYMPH', 'OCTET',
  'OFFAL', 'OPTIC', 'OVOID', 'OXIDE', 'PIXEL',
];

export const WORDS = [...EASY_WORDS, ...MEDIUM_WORDS, ...HARD_WORDS];

export const CLUES: Record<string, string> = {
  APPLE: 'A round fruit that grows on trees',
  BEACH: 'Sandy shore by the ocean',
  BREAD: 'Baked food made from flour and yeast',
  CHAIR: 'You sit on this piece of furniture',
  CLOCK: 'Shows you the time on a wall',
  CLOUD: 'White fluffy thing in the sky',
  DANCE: 'Move your body to music',
  DRINK: 'To swallow a liquid like water',
  EARTH: 'The planet we live on',
  FIELD: 'Open land for farming or sports',
  FRUIT: 'Sweet food that grows on plants',
  GLASS: 'You drink water from this',
  GRAPE: 'Small round fruit used for wine',
  GREEN: 'The color of grass and leaves',
  HEART: 'The organ that pumps your blood',
  HOUSE: 'A building where people live',
  JUICE: 'Liquid squeezed from fruit',
  LEMON: 'A sour yellow citrus fruit',
  LIGHT: 'Brightness that lets you see',
  MUSIC: 'Sounds and melodies you listen to',
  NIGHT: 'The dark time when the sun is down',
  OCEAN: 'The vast saltwater sea',
  PHONE: 'Device you use to call people',
  PIZZA: 'Round flat food with cheese on top',
  PLANT: 'A living thing that grows in soil',
  RADIO: 'Device that plays music and news',
  RIVER: 'A long stream of flowing water',
  SHIRT: 'Clothing you wear on your upper body',
  SHOES: 'You wear these on your feet',
  SMILE: 'A happy expression on your face',
  SNAKE: 'A long reptile with no legs',
  SPACE: 'The vast area beyond our sky',
  SPOON: 'Utensil used for eating soup',
  STORM: 'Heavy rain with thunder and wind',
  TABLE: 'Flat surface you eat meals on',
  TIGER: 'A large striped wild cat',
  TOAST: 'Browned bread from a toaster',
  TRAIN: 'Long vehicle that runs on tracks',
  TRUCK: 'Large vehicle for carrying goods',
  VOICE: 'The sound you make when speaking',
  WATCH: 'Small clock worn on your wrist',
  WATER: 'Clear liquid essential for life',
  WHALE: 'The largest animal in the ocean',
  WORLD: 'The entire Earth and everyone on it',
  YOUTH: 'The early period of being young',

  BRAIN: 'The organ inside your head that thinks',
  BRUSH: 'Tool with bristles for hair or painting',
  CHEST: 'The front part of your upper body',
  CHORD: 'Multiple musical notes played together',
  CLICK: 'A short sharp sound from a button',
  DIARY: 'A private book where you write daily',
  DRIVE: 'To operate and steer a car',
  FEAST: 'A large celebratory meal',
  GUARD: 'A person who protects a place',
  PIANO: 'A large musical instrument with keys',
  PILOT: 'Person who flies an aircraft',
  PLANE: 'A vehicle that flies in the sky',
  ROBOT: 'A machine that can do tasks automatically',
  TOUCH: 'To feel something with your hand',
  WRITE: 'To put words on paper',
  BLAZE: 'A large and fierce fire',
  CRISP: 'Firm and fresh, like a good apple',
  DWARF: 'A fairy tale creature, short and stout',
  FLAIR: 'A natural talent or style',
  GLOOM: 'A state of darkness or sadness',
  GROAN: 'A low sound of pain or annoyance',
  HASTE: 'Doing something too quickly',
  KNEEL: 'To rest on your knees',
  LODGE: 'A small house in the countryside',
  MAPLE: 'A tree known for its sweet syrup',
  NERVE: 'Fiber that carries signals in your body',
  ORBIT: 'The path a planet takes around a star',
  PERCH: 'A spot where a bird sits or rests',
  QUILT: 'A warm padded blanket on a bed',
  RIDGE: 'A long narrow raised strip of land',
  SCALP: 'The skin on top of your head',
  SHRUG: 'To raise your shoulders in doubt',
  SLUMP: 'A sudden drop or collapse',
  SNARE: 'A trap used to catch animals',
  SPIRE: 'A tall pointed structure on a church',
  STOMP: 'To walk with heavy forceful steps',
  SWAMP: 'A wet marshy area of land',
  THORN: 'A sharp point on a plant stem',
  TROUT: 'A freshwater fish with speckled skin',
  VAULT: 'A secure room for storing valuables',
  WALTZ: 'A graceful ballroom dance in triple time',
  WHIRL: 'To spin around quickly',
  WRATH: 'Extreme anger or fury',
  ZEBRA: 'An African animal with black and white stripes',
  ZONAL: 'Relating to or arranged in zones',

  ABBEY: 'A building where monks or nuns live',
  AXIOM: 'A statement accepted as true without proof',
  BLUNT: 'Not sharp, or speaking too directly',
  BYLAW: 'A rule made by a local authority',
  CHASM: 'A deep crack or gap in the earth',
  CINCH: 'Something very easy to do',
  CLEFT: 'A split or divided opening',
  CRYPT: 'An underground burial chamber',
  CYNIC: 'Someone who doubts people are sincere',
  DIRGE: 'A sad funeral song or lament',
  DROSS: 'Waste material or worthless stuff',
  EPOCH: 'A long distinct period of history',
  EXPEL: 'To force someone to leave a place',
  EXTOL: 'To praise something very highly',
  FJORD: 'A narrow sea inlet between tall cliffs',
  FLECK: 'A tiny spot or speck of something',
  FROZE: 'Turned solid from extreme cold',
  GLYPH: 'A carved symbol or character',
  GNASH: 'To grind your teeth together',
  GRUFF: 'Rough and unfriendly in manner',
  GUILD: 'An association of craftsmen or traders',
  GUSTO: 'Great energy and enthusiasm',
  GYPSY: 'A person who travels from place to place',
  HAVOC: 'Widespread chaos and destruction',
  HELIX: 'A spiral shape like a corkscrew',
  HIPPO: 'A large thick-skinned African animal',
  HOVEL: 'A small dirty poorly built house',
  HYENA: 'A dog-like African animal that laughs',
  IGLOO: 'A dome-shaped house made of snow',
  INEPT: 'Clumsy or lacking skill',
  IRONY: 'When the opposite of what you expect happens',
  IVORY: 'The hard white material from elephant tusks',
  JAZZY: 'Lively and flashy in style',
  JOUST: 'A medieval knight contest with lances',
  KNACK: 'A natural skill or ability',
  KNAVE: 'A dishonest or tricky person',
  LYMPH: 'A clear fluid in your immune system',
  MAXIM: 'A short clever saying or rule',
  MELEE: 'A confused crowd fight or scuffle',
  MIRTH: 'Great amusement and laughter',
  MOULT: 'To shed old feathers or skin',
  MURKY: 'Dark, gloomy, and unclear',
  MYRRH: 'A fragrant resin used in incense',
  NYMPH: 'A nature spirit from Greek mythology',
  OCTET: 'A group of eight people or things',
  OFFAL: 'The waste parts of a butchered animal',
  OPTIC: 'Relating to the eye or vision',
  OVOID: 'Egg-shaped in form',
  OXIDE: 'A chemical compound with oxygen',
  PIXEL: 'A tiny dot on a digital screen',
};
